# Generated by Django 2.0.3 on 2018-03-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(default=0),
        ),
    ]
