# Generated by Django 2.0.3 on 2018-03-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20180331_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.IntegerField(choices=[(0, '647M'), (1, '649M'), (2, '646M')], default=0),
        ),
    ]
