# Generated by Django 2.0.4 on 2018-04-30 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20180331_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(default=0, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(default=0, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default=0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='lessons.Audience')),
                ('day_of_week', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='lessons.DayOfWeek')),
                ('discipline', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='lessons.Discipline')),
                ('group', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='lessons.Group')),
            ],
        ),
        migrations.CreateModel(
            name='WeekType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_type', models.IntegerField(choices=[(0, 'Any_Week'), (1, 'Down_Week'), (2, 'Up_Week')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='day',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title',
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lesson',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='lessons.Lesson'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lesson_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='lessons.LessonType'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='week_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='lessons.WeekType'),
        ),
        migrations.AlterUniqueTogether(
            name='dayofweek',
            unique_together={('id', 'day_of_week')},
        ),
    ]
